[project]
name = "multi-agentes-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "exa-py>=1.43.0",
    "google-genai>=1.73.1",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.17.1",
    "sentence-transformers>=4.1.0",
    "sqlalchemy>=2.0.49",
]

[tool.uv]
package = false
